name: Check Branch Naming Convention

on:
  pull_request:
    branches:
      - '*'  # ตรวจสอบทุก branch

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check if branch name follows the convention
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          
          # เช็คว่าชื่อ branch ต้องมี prefix เช่น 'feature/' หรือ 'bugfix/'
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|release)/ ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow the required naming convention."
            exit 1
          else
            echo "Branch name '$BRANCH_NAME' follows the naming convention."
          fi
