name: PR Target Branch and Assign Reviewers

on:
  pull_request:
    branches:
      - master  # ระบุชื่อ branch เป้าหมายที่คุณต้องการ เช่น main, develop

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Determine the reviewer based on source branch name
        id: set-reviewer
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" == *"out"* ]]; then
            echo "::set-output name=reviewer::Theerapat-dev"
          else
            echo "::set-output name=none"
          fi

      - name: Add reviewer to the pull request
        if: steps.set-reviewer.outputs.reviewer != 'none'
        run: |
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            -d '{"reviewers":["${{ steps.set-reviewer.outputs.reviewer }}"]}'
